# Generated by Django 5.2.3 on 2025-06-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_avatar_url_user_discord_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="avatar_url",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_username",
        ),
    ]
