# Generated by Django 5.2.3 on 2025-06-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artifacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revision",
            options={
                "ordering": ["-datetime"],
                "permissions": [
                    (
                        "manage_revisions",
                        "Can pin, hide, and schedule revisions for deletion",
                    )
                ],
            },
        ),
    ]
